services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: exerciselog
      POSTGRES_USER: exerciselog_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /run/secrets:/run/secrets:ro

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: exerciselog-app-backend
    ports:
      - "8080:8080"
    volumes:
      - /run/secrets:/run/secrets:ro
    depends_on:
      - postgres

volumes:
  postgres-data:
    external: true
    name: exerciselog-app_postgres-data

